### ISSUE TITLE
Algo sale mal con los herores

### ISSUE THREAD

**Issue by jlozanof** [jlozanof/avenger#9]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by lpinos82** [comment]
Esto ya esta reuelto

**Comment by jlozanof** [comment]
ok de acuerdo






*seguro de su atención,*


*Joel Lozano*

*Analista de Sistemas & Marker Digital*


***@***.***
www. joellozano.net
